### PR TITLE
Update Readme with Sidekiq explanation

### PR DESCRIPTION
**Pull request by jphastings**
Running through an upgrade on Actor Tracking Service it wasn't clear as to _why_ custom sidekiq settings aren't allowed. Added this with @rxbynerd to help explain that.

### CODE REVIEW

**Comment by jphastings** [comment]
@danielcooper I'll let you review this and merge it at your own discretion :)

**Comment by jphastings** [comment]
Ahh it'll be up to @deliveroo/seti to do that :)

**Comment by humzashah** [comment]
@jphastings @rxbynerd FYI: this will soon be changing:
https://deliveroo.atlassian.net/browse/LOG-1564
https://deliveroo.atlassian.net/browse/LOG-1565

**Comment by jphastings** [comment]
Thanks @humzashah! This readme will probably need a slight tweak once that's done then — but it's probably worthwhile merging this still 😊

We also ran into trouble with the migration to the new queue names; I'm going to add another small section on migrating to this PR.

**Comment by jphastings** [comment]
FYI CodeClimate is being grumpy - it won't _allow_ a guard clause for such a long phrase (nor should it!) but the alternative - wrapping in a conditional - it also seems set to dislike.

**Comment by humzashah** [comment]
@jphastings have you tried:

```ruby
return unless File.exist?('config/sidekiq.yml')
fail! 'Custom Sidekiq settings found. Please see the Roo On Rails readme for more information'
```

**Pull request merged**
